### PR TITLE
Jenkins Pipeline - update golds test

### PR DESCRIPTION
**Pull request by serban-nicusor-toptal**
Create a new Jenkins manual pipeline for running the update-golds test and open a PR into the repository with the results.

### CODE REVIEW

**Comment by serban-nicusor-toptal** [comment]
Hey @WardBrian I've created this PR for setting up the Jenkins pipeline we need, it does throw some errors:
```
clang: error: no such file or directory: '../stat_comp_benchmarks/benchmarks/low_dim_corr_gauss/low_dim_corr_gauss.o'
clang: error: no such file or directory: '../stat_comp_benchmarks/benchmarks/pkpd/one_comp_mm_elim_abs.o'
clang: error: no such file or directory: '../stat_comp_benchmarks/benchmarks/low_dim_gauss_mix/low_dim_gauss_mix.o'
clang: error: no such file or directory: '../stat_comp_benchmarks/benchmarks/pkpd/sim_one_comp_mm_elim_abs.o'
```
These errors are on the master run also, do you know by any chance how we can tackle them? Thanks!

**Comment by WardBrian** [comment]
Can I see the run somewhere?

**Comment by serban-nicusor-toptal** [comment]
See: https://jenkins.flatironinstitute.org/blue/organizations/jenkins/Stan%2FUpdate-golds/detail/Update-golds/5/pipeline

**Comment by WardBrian** [comment]
Huh, I have no earthly idea. I think we've all just been ignoring the `master` failures because of #49/#50

**Comment by WardBrian** [comment]
@serban-nicusor-toptal the same command for me locally succeeds in building all the models

**Comment by serban-nicusor-toptal** [comment]
Good morning @WardBrian, this [looks good](https://jenkins.flatironinstitute.org/blue/organizations/jenkins/Stan%2FUpdate-golds/detail/Update-golds/10/pipeline) now.
Do we need to keep the .csv and .xml files ? https://github.com/stan-dev/performance-tests-cmdstan/pull/54/files
PS: I moved it from OSX to Linux, not sure why it's not working on mac.

**Comment by WardBrian** [comment]
We don't want the csv or xml

**Comment by WardBrian** [comment]
Moving to linux might be problematic since the specific issue we were having in #49 is machine-specific I believe

**Comment by serban-nicusor-toptal** [comment]
I'll debug Mac a bit more later and see if I figure it out.

**Comment by serban-nicusor-toptal** [comment]
Looks like they run completely different things on linux and mac.
On linux it starts with a make command:
```
make -i -j8 ../stat_comp_benchmarks/benchmarks/arK/arK ../stat_comp_benchmarks/benchmarks/arma/arma ../stat_comp_benchmarks/benchmarks/eight_schools/eight_schools ../stat_comp_benchmarks/benchmarks/garch/garch ../stat_comp_benchmarks/benchmarks/gp_pois_regr/gp_pois_regr ../stat_comp_benchmarks/benchmarks/gp_regr/gen_gp_data ../stat_comp_benchmarks/benchmarks/gp_regr/gp_regr ../stat_comp_benchmarks/benchmarks/irt_2pl/irt_2pl ../stat_comp_benchmarks/benchmarks/low_dim_corr_gauss/low_dim_corr_gauss ../stat_comp_benchmarks/benchmarks/low_dim_gauss_mix/low_dim_gauss_mix ../stat_comp_benchmarks/benchmarks/pkpd/one_comp_mm_elim_abs ../stat_comp_benchmarks/benchmarks/sir/sir ../stat_comp_benchmarks/benchmarks/pkpd/sim_one_comp_mm_elim_abs
```

On mac it starts with a clang++ call to compile these models:
```
clang++ -march=core2  -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare -D_REENTRANT -Wno-ignored-attributes      -I stan/lib/stan_math/lib/tbb_2020.3/include    -O3 -I src -I stan/src -I stan/lib/rapidjson_1.1.0/ -I lib/CLI11-1.9.1/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.4.0 -I stan/lib/stan_math/lib/boost_1.78.0 -I stan/lib/stan_math/lib/sundials_6.1.1/include -I stan/lib/stan_math/lib/sundials_6.1.1/src/sundials    -DBOOST_DISABLE_ASSERTS          -c -MT stan/src/stan/model/model_header_12_0.hpp.gch -MT stan/src/stan/model/model_header_12_0.d -MM -E -MG -MP -MF stan/src/stan/model/model_header_12_0.d stan/src/stan/model/model_header.hpp
```

Along the way on mac it seems to miss a bunch of PCH files:
```
--- Compiling C++ code ---
clang++ -march=core2  -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare -D_REENTRANT -Wno-ignored-attributes      -I stan/lib/stan_math/lib/tbb_2020.3/include    -O3 -I src -I stan/src -I stan/lib/rapidjson_1.1.0/ -I lib/CLI11-1.9.1/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.4.0 -I stan/lib/stan_math/lib/boost_1.78.0 -I stan/lib/stan_math/lib/sundials_6.1.1/include -I stan/lib/stan_math/lib/sundials_6.1.1/src/sundials    -DBOOST_DISABLE_ASSERTS          -c -include-pch stan/src/stan/model/model_header_12_0.hpp.gch -x c++ -o ../stat_comp_benchmarks/benchmarks/low_dim_gauss_mix/low_dim_gauss_mix.o ../stat_comp_benchmarks/benchmarks/low_dim_gauss_mix/low_dim_gauss_mix.hpp
error: unable to read PCH file stan/src/stan/model/model_header_12_0.hpp.gch: 'No such file or directory'
fatal error: PCH file 'stan/src/stan/model/model_header_12_0.hpp.gch' not found: module file not found
2 errors generated.
make: [../stat_comp_benchmarks/benchmarks/irt_2pl/irt_2pl.o] Error 1 (ignored)
```

And some `.o` files:
```
--- Linking model ---
clang++ -march=core2  -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare -D_REENTRANT -Wno-ignored-attributes      -I stan/lib/stan_math/lib/tbb_2020.3/include    -O3 -I src -I stan/src -I stan/lib/rapidjson_1.1.0/ -I lib/CLI11-1.9.1/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.4.0 -I stan/lib/stan_math/lib/boost_1.78.0 -I stan/lib/stan_math/lib/sundials_6.1.1/include -I stan/lib/stan_math/lib/sundials_6.1.1/src/sundials    -DBOOST_DISABLE_ASSERTS               -Wl,-L,"/Users/jenkins/workspace/Stan/Update-golds/cmdstan/stan/lib/stan_math/lib/tbb" -Wl,-rpath,"/Users/jenkins/workspace/Stan/Update-golds/cmdstan/stan/lib/stan_math/lib/tbb"        ../stat_comp_benchmarks/benchmarks/irt_2pl/irt_2pl.o src/cmdstan/main.o       -Wl,-L,"/Users/jenkins/workspace/Stan/Update-golds/cmdstan/stan/lib/stan_math/lib/tbb" -Wl,-rpath,"/Users/jenkins/workspace/Stan/Update-golds/cmdstan/stan/lib/stan_math/lib/tbb"     stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_nvecserial.a stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_cvodes.a stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_idas.a stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_kinsol.a  stan/lib/stan_math/lib/tbb/libtbb.dylib stan/lib/stan_math/lib/tbb/libtbbmalloc.dylib stan/lib/stan_math/lib/tbb/libtbbmalloc_proxy.dylib -o ../stat_comp_benchmarks/benchmarks/irt_2pl/irt_2pl
clang: error: no such file or directory: '../stat_comp_benchmarks/benchmarks/arK/arK.o'
clang: error: no such file or directory: '../stat_comp_benchmarks/benchmarks/arma/arma.o'
clang: error: no such file or directory: '../stat_comp_benchmarks/benchmarks/garch/garch.o'
clang: clang: error: no such file or directory: '../stat_comp_benchmarks/benchmarks/irt_2pl/irt_2pl.o'
error: no such file or directory: '../stat_comp_benchmarks/benchmarks/gp_regr/gp_regr.o'
clang: error: no such file or directory: '../stat_comp_benchmarks/benchmarks/gp_regr/gen_gp_data.o'
clang: error: no such file or directory: '../stat_comp_benchmarks/benchmarks/gp_pois_regr/gp_pois_regr.o'
make: clang: [../stat_comp_benchmarks/benchmarks/arK/arK] Error 1 (ignored)error: no such file or directory: '../stat_comp_benchmarks/benchmarks/eight_schools/eight_schools.o'

make: [../stat_comp_benchmarks/benchmarks/garch/garch] Error 1 (ignored)
make: [../stat_comp_benchmarks/benchmarks/arma/arma] Error 1 (ignored)
make: [../stat_comp_benchmarks/benchmarks/irt_2pl/irt_2pl] Error 1 (ignored)
make: [../stat_comp_benchmarks/benchmarks/gp_regr/gp_regr] Error 1 (ignored)
make: [../stat_comp_benchmarks/benchmarks/gp_regr/gen_gp_data] Error 1 (ignored)
make: [../stat_comp_benchmarks/benchmarks/gp_pois_regr/gp_pois_regr] Error 1 (ignored)

make: [../stat_comp_benchmarks/benchmarks/eight_schools/eight_schools] Error 1 (ignored)
```

And because of these .PCH and .O files, final compilation won't succeed and the make call fails:
```
--- Linking model ---
clang++ -march=core2  -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare -D_REENTRANT -Wno-ignored-attributes      -I stan/lib/stan_math/lib/tbb_2020.3/include    -O3 -I src -I stan/src -I stan/lib/rapidjson_1.1.0/ -I lib/CLI11-1.9.1/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.4.0 -I stan/lib/stan_math/lib/boost_1.78.0 -I stan/lib/stan_math/lib/sundials_6.1.1/include -I stan/lib/stan_math/lib/sundials_6.1.1/src/sundials    -DBOOST_DISABLE_ASSERTS               -Wl,-L,"/Users/jenkins/workspace/Stan/Update-golds/cmdstan/stan/lib/stan_math/lib/tbb" -Wl,-rpath,"/Users/jenkins/workspace/Stan/Update-golds/cmdstan/stan/lib/stan_math/lib/tbb"        ../stat_comp_benchmarks/benchmarks/pkpd/sim_one_comp_mm_elim_abs.o src/cmdstan/main.o       -Wl,-L,"/Users/jenkins/workspace/Stan/Update-golds/cmdstan/stan/lib/stan_math/lib/tbb" -Wl,-rpath,"/Users/jenkins/workspace/Stan/Update-golds/cmdstan/stan/lib/stan_math/lib/tbb"     stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_nvecserial.a stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_cvodes.a stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_idas.a stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_kinsol.a  stan/lib/stan_math/lib/tbb/libtbb.dylib stan/lib/stan_math/lib/tbb/libtbbmalloc.dylib stan/lib/stan_math/lib/tbb/libtbbmalloc_proxy.dylib -o ../stat_comp_benchmarks/benchmarks/pkpd/sim_one_comp_mm_elim_abs
clang: error: no such file or directory: '../stat_comp_benchmarks/benchmarks/sir/sir.o'
make: [../stat_comp_benchmarks/benchmarks/sir/sir] Error 1 (ignored)
clang: error: no such file or directory: '../stat_comp_benchmarks/benchmarks/pkpd/one_comp_mm_elim_abs.o'
clang: error: no such file or directory: '../stat_comp_benchmarks/benchmarks/low_dim_corr_gauss/low_dim_corr_gauss.o'
clang: error: no such file or directory: '../stat_comp_benchmarks/benchmarks/pkpd/sim_one_comp_mm_elim_abs.o'
clang: make: [../stat_comp_benchmarks/benchmarks/pkpd/one_comp_mm_elim_abs] Error 1 (ignored)
error: no such file or directory: '../stat_comp_benchmarks/benchmarks/low_dim_gauss_mix/low_dim_gauss_mix.o'
make: [../stat_comp_benchmarks/benchmarks/low_dim_corr_gauss/low_dim_corr_gauss] Error 1 (ignored)
make: [../stat_comp_benchmarks/benchmarks/pkpd/sim_one_comp_mm_elim_abs] Error 1 (ignored)
make: [../stat_comp_benchmarks/benchmarks/low_dim_gauss_mix/low_dim_gauss_mix] Error 1 (ignored)
rm ../stat_comp_benchmarks/benchmarks/sir/sir.hpp ../stat_comp_benchmarks/benchmarks/irt_2pl/irt_2pl.hpp ../stat_comp_benchmarks/benchmarks/gp_regr/gp_regr.hpp ../stat_comp_benchmarks/benchmarks/pkpd/one_comp_mm_elim_abs.hpp ../stat_comp_benchmarks/benchmarks/garch/garch.hpp ../stat_comp_benchmarks/benchmarks/arma/arma.hpp ../stat_comp_benchmarks/benchmarks/low_dim_gauss_mix/low_dim_gauss_mix.hpp ../stat_comp_benchmarks/benchmarks/pkpd/sim_one_comp_mm_elim_abs.hpp ../stat_comp_benchmarks/benchmarks/gp_pois_regr/gp_pois_regr.hpp ../stat_comp_benchmarks/benchmarks/eight_schools/eight_schools.hpp ../stat_comp_benchmarks/benchmarks/gp_regr/gen_gp_data.hpp ../stat_comp_benchmarks/benchmarks/low_dim_corr_gauss/low_dim_corr_gauss.hpp ../stat_comp_benchmarks/benchmarks/arK/arK.hpp
make -i -j8 ../stat_comp_benchmarks/benchmarks/arK/arK ../stat_comp_benchmarks/benchmarks/arma/arma ../stat_comp_benchmarks/benchmarks/eight_schools/eight_schools ../stat_comp_benchmarks/benchmarks/garch/garch ../stat_comp_benchmarks/benchmarks/gp_pois_regr/gp_pois_regr ../stat_comp_benchmarks/benchmarks/gp_regr/gen_gp_data ../stat_comp_benchmarks/benchmarks/gp_regr/gp_regr ../stat_comp_benchmarks/benchmarks/irt_2pl/irt_2pl ../stat_comp_benchmarks/benchmarks/low_dim_corr_gauss/low_dim_corr_gauss ../stat_comp_benchmarks/benchmarks/low_dim_gauss_mix/low_dim_gauss_mix ../stat_comp_benchmarks/benchmarks/pkpd/one_comp_mm_elim_abs ../stat_comp_benchmarks/benchmarks/sir/sir ../stat_comp_benchmarks/benchmarks/pkpd/sim_one_comp_mm_elim_abs
'stat_comp_benchmarks/benchmarks/arK/arK.stan' had fails '[]' and errors '['Did not compile!']'
'stat_comp_benchmarks/benchmarks/arma/arma.stan' had fails '[]' and errors '['Did not compile!']'
'stat_comp_benchmarks/benchmarks/eight_schools/eight_schools.stan' had fails '[]' and errors '['Did not compile!']'
'stat_comp_benchmarks/benchmarks/garch/garch.stan' had fails '[]' and errors '['Did not compile!']'
'stat_comp_benchmarks/benchmarks/irt_2pl/irt_2pl.stan' had fails '[]' and errors '['Did not compile!']'
'stat_comp_benchmarks/benchmarks/gp_regr/gen_gp_data.stan' had fails '[]' and errors '['Did not compile!']'
'stat_comp_benchmarks/benchmarks/low_dim_gauss_mix/low_dim_gauss_mix.stan' had fails '[]' and errors '['Did not compile!']'
'stat_comp_benchmarks/benchmarks/gp_regr/gp_regr.stan' had fails '[]' and errors '['Did not compile!']'
'stat_comp_benchmarks/benchmarks/sir/sir.stan' had fails '[]' and errors '['Did not compile!']'
'stat_comp_benchmarks/benchmarks/pkpd/sim_one_comp_mm_elim_abs.stan' had fails '[]' and errors '['Did not compile!']'
'stat_comp_benchmarks/benchmarks/pkpd/one_comp_mm_elim_abs.stan' had fails '[]' and errors '['Did not compile!']'
'stat_comp_benchmarks/benchmarks/low_dim_corr_gauss/low_dim_corr_gauss.stan' had fails '[]' and errors '['Did not compile!']'
'stat_comp_benchmarks/benchmarks/gp_pois_regr/gp_pois_regr.stan' had fails '[]' and errors '['Did not compile!']'
```

Looks like we might be missing a build flag `/Yc` to indicate we want to create the precompiled headers, not entirely sure how I can pass that to the clang++ call. ([see](https://stackoverflow.com/questions/6096384/how-to-fix-pch-file-missing-on-build))

**Comment by WardBrian** [comment]
I think we might just want to set PRECOMPILED_HEADERS=False in the make/local on mac. It will slow thing down but it's not that many models?

**Comment by serban-nicusor-toptal** [comment]
You were right on point! It seems to be working fine for now https://jenkins.flatironinstitute.org/blue/organizations/jenkins/Stan%2FUpdate-golds/detail/Update-golds/12/pipeline
I think we have about a dozen of them so we should be fine I think.

**Comment by WardBrian** [comment]
Can you make the same fix to the normal jenkinsfile?

**Comment by serban-nicusor-toptal** [comment]
If this looks good https://github.com/stan-dev/performance-tests-cmdstan/pull/57 then we're ready to merge.

**Comment by WardBrian** [comment]
I think this PR is good to go! #57 looks like I would expect, I want to look over the numbers before merging that but I think we can merge this one

**Pull request merged**
