### PR TITLE
Added custom Jenkinsfile

### PR DESCRIPTION
**Pull request by serban-nicusor-toptal**

### CODE REVIEW

**Comment by seantalts** [comment]
This one doesn't need the comment posting thing does it? 

What are the benefits of doing a clean checkout as a separate stage vs. just combining it with the stage in which it will run the tests?

**Comment by seantalts** [comment]
Also can you post a link to a run of this so I can take a look at it?

**Comment by serban-nicusor-toptal** [comment]
Removed comment logic.
I've put the clean checkout logic above so we separate it from the actual test logic, looks better to me. If you don't like it I can put them inside the other blocks.

You can see a success of the job here:
https://jenkins.mc-stan.org/job/CmdStan%20Performance%20Tests/job/Custom/32/console

And a failure here:
https://jenkins.mc-stan.org/job/CmdStan%20Performance%20Tests/job/Custom/33/console

**Comment by seantalts** [comment]
Gotcha, thanks. Could you remove the performance tracking of the stuff? it's a little misleading since it's uploading develop xmls but we really just care about relative performance, which is just output into the console

**Pull request closed without merging**
