### PR TITLE
Fix stdev calculation

### LINKED ISSUE #29: Typo in `stdev` in runPerformanceTests.py?
The definition of `stdev` in runPerformanceTests.py is a bit odd.

```python
def stdev(coll, mean):
    if len(coll ) < 2:
        return 0
    return (sum((x - mean)**2 for x in coll) / (len(coll) - 1)**0.5)
```

Looks like the last parenthesis is misplaced.
```python
(sum((x - mean)**2 for x in coll) / (len(coll) - 1))**0.5
```

If this is a typo, the fix will probably impact the results stored in the `golds` directory.
E.g. https://github.com/stan-dev/performance-tests-cmdstan/blob/master/golds/stat_comp_benchmarks_benchmarks_eight_schools_eight_schools.gold

### PR DESCRIPTION
**Pull request by WardBrian**
Closes #29

We were in fact incorrectly calculating the standard deviation in the golds files.

### CODE REVIEW

**Review by rok-cesnovar — APPROVED** [review]
Nice one!

**Comment by WardBrian** [comment]
@rok-cesnovar do you know if we want the population standard deviation instead? or if it matters?

**Comment by rok-cesnovar** [comment]
Sorry, I honestly don't know if we need it.

**Comment by WardBrian** [comment]
It looks like the original was using the definition of `stdev` for samples, which is what `statistics.stddev` does so I think this is fine

**Comment by WardBrian** [comment]
This seems to have broken the stan-dev/stan tests - it seems our CI Mac may still be running python 2?

**Comment by rok-cesnovar** [comment]
Sure as well could be yeah. @serban-nicusor-toptal do you know?

**Comment by WardBrian** [comment]
If we have python3 available, I think we can just change either the shebang line here or run them in the jenkinsfile with `python3 ./run...`

**Comment by serban-nicusor-toptal** [comment]
**[gelman-group-mac](https://jenkins.flatironinstitute.org/computer/gelman-group-mac/)**:

--- python --version
Python 2.7.15
--- python3 --version
Python 3.9.0

**[flatiron mac](https://jenkins.flatironinstitute.org/computer/mac/)**:

--- python --version
Python 2.7.16
--- python3 --version
Python 3.8.2

**[old-imac](https://jenkins.flatironinstitute.org/computer/old-imac)**:
--- python --version
Python 2.7.15
--- python3 --version
Python 3.4.2

Please let me know if I should update/align these versions or help with anything else.

**Comment by WardBrian** [comment]
I believe all of those are fine, we just need to specifically use python3 in the Stan jenkinsfile then

**Pull request merged**
